version: 0.0
os: linux
files:
  - source: s3app.run
    destination: /opt/appuser
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: appuser
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
