version: 0.0
os: linux
files:
  - source: /
    destination: /opt/appuser
hooks:
  Install:
    - location: scripts/start_server
      timeout: 300
      runas: appuser
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
