version: 0.0
os: linux
files:
  - source: /
    destination: /opt/appuser
permissions:
  - object: /opt/appuser
    pattern: "**"
    owner: appuser
    group: appuser
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: appuser
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
